#!/usr/bin/bash

export MAKEOPTS="-j4"

export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu --enable-re2c-cgoto --enable-rpath --enable-cli --enable-embed=shared --enable-fpm --with-fpm-systemd --with-fpm-acl --with-fpm-apparmor --enable-phpdbg --enable-phpdbg-readline --enable-cgi --with-valgrind --enable-litespeed --enable-zts --enable-libgcc --enable-ipv6 --enable-dtrace --with-libxml --with-openssl --with-kerberos --with-system-ciphers --with-pcre-jit --with-sqlite3 --with-zlib --enable-bcmath --with-bz2=/usr --enable-calendar --enable-ctype --with-curl --enable-dba --with-gdbm --with-db4 --with-tcadb --with-lmdb --with-cdb --enable-inifile --enable-flatfile --enable-dom --enable-dl-test --with-enchant --enable-exif --with-ffi --enable-fileinfo --enable-filter --enable-ftp --with-openssl-dir --enable-gd=/usr --with-avif --with-webp --with-jpeg --with-xpm --with-freetype --enable-gd-jis-conv --with-gettext --with-gmp --with-mhash --with-iconv --with-imap=/home/php-reqs/imap-src --with-kerberos --with-imap-ssl=/usr --enable-intl --with-ldap --with-ldap-sasl --enable-mbstring --enable-mbregex --with-mysqli=mysqlnd --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-oci8=shared,instantclient,/opt/oracle/instantclient  --with-odbcver=0 --with-unixODBC --enable-opcache --enable-huge-code-pages --enable-opcache-jit --enable-pcntl --enable-pdo --with-pdo-dblib --with-pdo-firebird --with-pdo-mysql=mysqlnd --with-pdo-oci=instantclient,/opt/oracle/instantclient --with-pdo-odbc=unixODBC,/usr --with-pdo-pgsql=/usr/bin --with-pdo-sqlite --with-pgsql --enable-phar --enable-posix --with-pspell --with-libedit --with-readline --enable-session --enable-shmop --enable-simplexml --with-snmp --enable-soap --enable-sockets --with-sodium --with-password-argon2 --enable-sysvmsg --enable-sysvsem --enable-sysvshm --with-tidy --enable-tokenizer --enable-xml --with-expat --enable-xmlreader --enable-xmlwriter --with-xsl --enable-zend-test --with-zip --enable-mysqlnd --enable-mysqlnd-compression-support --with-pear --enable-fiber-asm --enable-shared --enable-static --enable-fast-install"

export PHP_CONFIGURE_OPTS=$PHP_BUILD_CONFIGURE_OPTS

export PYTHON_CONFIGURE_OPTS="--enable-shared --enable-optimizations --enable-loadable-sqlite-extensions --enable-ipv6 --enable-big-digits=30 --enable-test-modules --with-pkg-config=check --with-static-libpython --with-lto=full --with-computed-gotos --with-hash-algorithm=siphash13 --with-system-ffi --with-system-expat --with-system-libmpdec --with-decimal-contextvar --with-dbmliborder=gdbm:ndbm:bdb --with-doc-strings --with-pymalloc --with-freelists --with-c-locale-coercion --with-valgrind --with-dtrace --with-platlibdir=lib --with-readline --with-ensurepip=upgrade --with-openssl=/usr --with-builtin-hashlib-hashes=md5,sha1,sha256,sha512,sha3,blake2"

export RUBY_CONFIGURE_OPTS="--disable-werror --enable-fortify-source --enable-largefile --enable-setreuid --enable-rpath --enable-multiarch --enable-shared --enable-pie --enable-dtrace --enable-ipv6 --enable-install-doc --enable-install-rdoc --enable-install-capi --enable-jit-support --enable-yjit --enable-install-static-library --enable-dln --enable-rubygems --with-git --with-gcc --with-compress-debug-sections=no --with-jemalloc --with-gmp --with-valgrind --with-rdoc=ri,html --with-mantype=man --with-openssl-dir=/usr --disable-install-doc"

export R_CONFIGURE_OPTS="--enable-R-profiling --enable-memory-profiling --enable-R-shlib --enable-BLAS-shlib --disable-prebuilt-html --enable-lto --enable-java --enable-byte-compiled-packages --enable-static --enable-shared --enable-fast-install --enable-long-double --enable-openmp --enable-largefile --enable-nls --enable-rpath --with-blas --with-lapack --with-readline --with-pcre2 --with-pcre1 --with-tcltk --with-cairo --with-libpng --with-jpeglib --with-libtiff --with-system-tre --with-valgrind-instrumentation=1 --with-system-valgrind-headers --with-internal-tzcode --with-internal-towlower --with-internal-iswxxxxx --with-internal-wcwidth --with-recommended-packages --with-ICU --with-static-cairo --with-aix-soname=both --with-x"

export NODE_CONFIGURE_OPTS="--no-cross-compiling --gdb --partly-static --enable-lt --openssl-is-fips --with-ossfuzz --with-dtrace --enable-asan --without-inspector --v8-enable-hugepage --shared-libuv --shared-nghttp2 --shared-nghttp3 --shared-ngtcp2 --shared-openssl --shared-zlib --shared-brotli --shared-cares"

export PERL_BUILD_CONFIGURE_OPTS=(-Duse64bitall -Duse64bitint -Dusecbacktrace -Dusedevel -Dusedl -Dusedtrace -Dusefaststdio=y -Dd_faststdio=y -Duseithreads=y -Duselanginfo -Duselargefiles -Duselongdouble -Dusemallocwrap -Dusemorebits -Dusemultiplicity -Dusemymalloc=y -Duseperlio=y -Duseopcode -Duseposix=true -Dusereentrant -Duseshrplib=y -Dusesitecustomize -Dusethreads=y -Dusevfork -Doptimize=-O2)

export ERLANG_CONFIGURE_OPTS="--enable-dirty-schedulers --enable-parallel-configure --enable-plain-emulator --enable-kernel-poll --enable-sctp --enable-vm-probes --enable-megaco-flex-scanner-lineno --enable-megaco-reentrant-flex-scanner --enable-dynamic-ssl-lib --enable-fips --enable-builtin-zlib --enable-esock --enable-sharing-preserving --enable-m64-build --enable-pie --with-termcap --with-dynamic-trace=dtrace --with-javac --with-ssl --with-ssl-rpath=yes --enable-ei-dynamic-lib"

export OCTAVE_CONFIGURE_OPTS="--disable-option-checking --enable-dependency-tracking --enable-std-pmr-polymorphic-allocator --enable-largefile --enable-year2038 --enable-threads=isoc+posix --enable-64 --enable-static --enable-shared --enable-fast-install --enable-libtool-lock --enable-link-all-dependencies --enable-float-truncate --enable-cross-tools --enable-rpath --enable-rapidjson --enable-readline --enable-command-line-push-parser --enable-fftw-threads --enable-java --enable-docs --enable-relocate-all --enable-hg-id --with-shell --with-system-freefont=/usr --with-aix-soname=both --with-blas=libblas64.so --with-lapack=liblapack64.so --with-openssl --with-qhull_r --with-libiconv --with-pcre --with-z --with-bz2 --with-hdf5 --with-fftw3 --with-fftw3f --with-glpk --with-curl --with-sndfile --with-portaudio --with-magick=GraphicsMagick++ --with-x --with-framework-carbon --with-opengl --with-framework-opengl --with-freetype --with-fontconfig --with-qt --with-qscintilla --with-fltk --with-qrupdate --with-suitesparseconfig --with-amd --with-camd --with-colamd --with-ccolamd --with-cholmod --with-spqr --with-cxsparse --with-umfpack --with-klu --with-sundials_nvecseria --with-sundials_ida --with-sundials_sunlinsolklu --with-arpack --enable-mpi"
