[extensions]
extension = bcmath.so
extension = bz2.so
extension = calendar.so
extension = ctype.so
extension = curl.so
extension = dba.so
extension = dl_test.so
extension = dom.so
extension = enchant.so
extension = exif.so
extension = ffi.so
extension = fileinfo.so
extension = filter.so
extension = ftp.so
extension = gd.so
extension = gettext.so
extension = gmp.so
extension = iconv.so
extension = intl.so
extension = ldap.so
extension = mbstring.so

; The mysqlnd extension is required by mysqli and pdo_mysql, so it must be loaded before them.
extension = mysqlnd.so

extension = mysqli.so
extension = odbc.so
extension = openssl.so
extension = pcntl.so
extension = pdo.so
extension = pdo_dblib.so
extension = pdo_firebird.so
extension = pdo_mysql.so
extension = pdo_odbc.so
extension = pdo_pgsql.so
extension = pdo_sqlite.so
extension = pgsql.so
extension = phar.so
extension = posix.so
extension = session.so
extension = shmop.so
extension = simplexml.so
extension = snmp.so
extension = soap.so
extension = sockets.so
extension = sodium.so
extension = sqlite3.so
extension = sysvsem.so
extension = sysvshm.so
extension = sysvmsg.so
extension = tidy.so
extension = tokenizer.so
# extension = xdebug.so
extension = xml.so
extension = xmlreader.so
extension = xmlwriter.so
extension = xsl.so
extension = zend_test.so
extension = zip.so
extension = zlib.so

[phar]
phar.readonly = Off

[xdebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1

