#!/usr/bin/env bash

export ERLANG_CONFIGURE_OPTS="
  --enable-parallel-configure
  --enable-dirty-schedulers
  --enable-plain-emulator
  --enable-kernel-poll
  --enable-sctp
  --enable-vm-probes
  --enable-megaco-flex-scanner-lineno
  --enable-megaco-reentrant-flex-scanner
  --enable-dynamic-ssl-lib
  --enable-builtin-zlib
  --enable-esock
  --enable-sharing-preserving
  --enable-m64-build
  --enable-pie
  --enable-largefile
  --enable-year2038
  --with-termcap
  --with-dynamic-trace=dtrace
  --with-javac
  --with-ssl
  --with-ssl-rpath=yes
"

# export KERL_CONFIGURE_OPTIONS="$ERLANG_CONFIGURE_OPTS"
