#!/usr/bin/env bash

export PERL_CONFIGURE_OPTS=(
  -Dusethreads
  -Duseithreads
  -Duselargefiles
  -Duse64bitint
  -Duse64bitall
  -Duselongdouble
  -Dusemorebits
  -Dusedl
  -Duseshrplib
  -Dusedtrace
  -Dusemymalloc
  -Dusevfork
  -Dusecbacktrace
  -Dusedevel
  -Dusefaststdio
  -Dd_faststdio
  -Duselanginfo
  -Dusemallocwrap
  -Dusemultiplicity
  -Duseperlio
  -Duseopcode
  -Duseposix
  -Dusereentrant
  -Dusesitecustomize
  -Dusevfork
  -Uversiononly
  -Doptimize=-Os
  -Accflags=-Os
  -Accflags=-s
  -Accflags=-march=native
  -Accflags=-mtune=native
  -Aldflags=-s
)
