#!/usr/bin/env bash

export RUBY_CONFIGURE_OPTS="
  --enable-rpath
  --enable-devel
  --disable-werror
  --enable-fortify-source
  --enable-largefile
  --enable-setreuid
  --enable-multiarch
  --enable-shared
  --enable-pie
  --enable-dtrace
  --enable-ipv6
  --enable-install-doc
  --enable-install-rdoc
  --disable-install-capi
  --enable-install-static-library
  --enable-yjit
  --enable-rjit
  --enable-dln
  --enable-debug-env
  --enable-mkmf-verbose
  --enable-rubygems
  --with-git
  --with-gcc
  --with-thread=pthread
  --with-jemalloc
  --with-coroutine
  --with-valgrind
  --with-rdoc=ri
  --with-mantype=man
"
