#!/usr/bin/env bash

export PERL_BUILD_CONFIGURE_OPTS=(
  -Dusethreads
  -Duseithreads
  -Duselargefiles
  -Duse64bitint
  -Duse64bitall
  -Duselongdouble
  -Dusemorebits
  -Dusedl
  -Duseshrplib
  -Dusedtrace
  -Dusemymalloc
  -Dusevfork
  -Dusecbacktrace
  -Dusedevel
  -Dusefaststdio
  -Dd_faststdio
  -Duselanginfo
  -Dusemallocwrap
  -Dusemultiplicity
  -Duseperlio
  -Duseopcode
  -Duseposix
  -Dusereentrant
  -Dusesitecustomize
  -Dusevfork
  -Doptimize=-O2
)
