#!/usr/bin/env bash

export RUBY_CONFIGURE_OPTS="
  --enable-rpath
  --disable-werror
  --enable-fortify-source
  --enable-largefile
  --enable-setreuid
  --enable-setreuid
  --enable-multiarch
  --enable-shared
  --enable-pie
  --enable-dtrace
  --enable-ipv6
  --disable-install-doc
  --enable-install-rdoc
  --enable-install-capi
  --enable-install-static-library
  --enable-yjit
  --enable-rjit
  --enable-dln
  --enable-rubygems
  --with-git
  --with-gcc
  --with-jemalloc
  --with-valgrind
  --with-rdoc=ri,html
  --with-mantype=man
  --with-openssl-dir=/usr
"
